//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstWebsite_Plaza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string CompanyPhone { get; set; }
        public int PlazaPlazaNo { get; set; }
    }
}
