//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstWebsite_Plaza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int PersonnelNo { get; set; }
        public string PersonnelName { get; set; }
        public string PersonnelAdress { get; set; }
        public string PersonnelPhone { get; set; }
        public int DepartmentDepartmentNo { get; set; }
    }
}
