//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstWebsite_Plaza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plaza
    {
        public int PlazaNo { get; set; }
        public string PlazaName { get; set; }
        public string PlazaAdress { get; set; }
        public string CompanyPhone { get; set; }
    }
}
